### PR TITLE
add auto device detection

### PR DESCRIPTION
**Pull request by Tole-k**
uses pytorch detection functions

### CODE REVIEW

**Comment by Dawid64** [comment]
Wouldn't be better not to detect device multiple times during the code execution? In case of using multiple classifiers?
It probably would be better to make this operation once, and remember the value, and then just call config.device, rather than additional function.
For architecture I recommend using getter and setter in config, it gives more flexibility and should allow assigning 'auto' and changing the value to actual device when needed.
Additionally if making double if statement for deciding the device wasn't intended as a well-made joke, consider making it more readable.

**Review by Dawid64 — CHANGES_REQUESTED** [review]
Available device should not change during execution

**Comment by Tole-k** [comment]
> Wouldn't be better not to detect device multiple times during the code execution? In case of using multiple classifiers? It probably would be better to make this operation once, and remember the value, and then just call config.device, rather than additional function. For architecture I recommend using getter and setter in config, it gives more flexibility and should allow assigning 'auto' and changing the value to actual device when needed. Additionally if making double if statement for deciding the device wasn't intended as a well-made joke, consider making it more readable and intuitive.

We could perform detection once and then remember the proper device only if we know certainly what the top-level function will be, if were to add detection to e.g. turbo_ml/turbo_ml_experimental init calls we wouldn't be able to tun functions such as generate_dataset or optimize_nn_parameters directly with auto parameter

**Comment by Dawid64** [comment]
> We could perform detection once and then remember the proper device only if we knew certainly what the top-level function will be, if were to add detection to e.g. turbo_ml/turbo_ml_experimental init calls we wouldn't be able to run functions such as generate_dataset or optimize_nn_parameters directly with auto parameter

Yes, but you can add this functionality in getter, as getters can perform operations, then, no matter of function order, the device will be detected exactly one time at the first call of the function. I believe it should solve the problem and provide simple interface.

**Comment by Tole-k** [comment]
> > We could perform detection once and then remember the proper device only if we knew certainly what the top-level function will be, if were to add detection to e.g. turbo_ml/turbo_ml_experimental init calls we wouldn't be able to run functions such as generate_dataset or optimize_nn_parameters directly with auto parameter
> 
> Yes, but you can add this functionality in getter, as getters can perform operations, then, no matter of function order, the device will be detected exactly one time at the first call of the function. I believe it should solve the problem and provide simple interface.

OK, i think i got you now, seems smart, i can do it

**Comment by Tole-k** [comment]
> Wouldn't be better not to detect device multiple times during the code execution? In case of using multiple classifiers? It probably would be better to make this operation once, and remember the value, and then just call config.device, rather than additional function. For architecture I recommend using getter and setter in config, it gives more flexibility and should allow assigning 'auto' and changing the value to actual device when needed. Additionally if making double if statement for deciding the device wasn't intended as a well-made joke, consider making it more readable and intuitive.

could you clarify, was my solution too one-line'y or not enough one-line'y ?

**Comment by Dawid64** [comment]
> could you clarify, was my solution too one-line'y or not enough one-line'y ?
for maintenance purposes it's better to avoid things like: `1 if 1 else 2 if 0 else 0` (I think it's rather tricky sometimes)
But if you want to keep it feel free

**Review by Dawid64 — COMMENTED** [review]
Okey, It looks better, small additional comments
You can consider using @property and @device.setter, it should make interface nicer.
And I think it would be better to remove device argument from all non-highest level function, as well as setters, and use getters only at the lowest level functions.

**Comment by Tole-k** [comment]
> Okey, It looks better, small additional comments You can consider using @Property and @device.setter, it should make interface nicer. And I think it would be better to remove device argument from all non-highest level function, as well as setters, and use getters only at the lowest level functions.

wouldn't @device.setter require us to initialize and share the instance of options class among all functions?
also, we can't really be sure what the highest-level functions are, we might in the future want to call some functions directly

**Comment by Dawid64** [comment]
> wouldn't @device.setter require us to initialize and share the instance of options class among all functions? also, we can't really be sure what the highest-level functions are, we might in the future want to call some functions directly

I mean if someone would want to use middle level function for example for development purposes, and he would want to choose non-automatic device he can just set in config the device.

About setter your right, I totally forgot about that :(. It's seems like currently there isn't any alternative that works for classes, so there are few options to work that around as for example calling `config = config()` at the end of the file or creating custom descriptor, but it's not too nice, but I heard the rumor, that the new python library with such decorators and many others may be published in the next week, maybe we should use it?

**Comment by Dawid64** [comment]
> 
> So, do you happen to know whether that library solves our issue? I reckon you might know something about it

Sorry for keep you waiting. Unfortunately programmers mentioned before weren't powerful enough to make this idea on time, and they ended up providing half-done product. I think we should just go with brutal, however effective way:
`config = config()`. It should do the trick. If developers in some distant future make improve library we may reconsider using it for that task.

**Review by Dawid64 — APPROVED** [review]

**Review by Dawid64 — CHANGES_REQUESTED** [review]
### Looks much better now!
Not sure if using default values in setter (device setter) is good option, it may to lead **unpredictable behavior**
and I think that getters and setters for other things like threads dev_mode or other things are unnecessary, as it's not necessarily considered as a good behavior in python, so I would consider removing them.
No remarks other than that.

**Review by Dawid64 — APPROVED** [review]
LGTM 👍

**Pull request merged**
