### PR TITLE
Bootleg AutoIrad Implementation

### PR DESCRIPTION
**Pull request by Tole-k**

### CODE REVIEW

**Review by Dawid64 — CHANGES_REQUESTED** [review]
Creating that many even light weight files, is not a good practice, I know they are light weighted, but this is still too much (even GitHub has trouble displaying them). I don't think it's good idea to merge this into paper in such form. If all 1k files are neccessary, we can keep up on separate branch.

**Comment by adamtms** [comment]
> > Creating that many even light weight files, is not a good practice, I know they are light weighted, but this is still too much (even GitHub has trouble displaying them). I don't think it's good idea to merge this into paper in such form. If all 1k files are neccessary, we can keep up on separate branch.
> 
> Isn't that the point of DVC to store light index files on version control while data itself is stored somewhere else? and don't we want to have all things relevant to the paper in one place? Generating those images takes long time so it's much better to share them than generate from scratch more than once

Since these files do not get updated a lot maybe we could zip these files and keep track of one big zip file in dvc. We wouldnt have a mess on dvc then and we would still save all of the data,

**Comment by Tole-k** [comment]
> > > Creating that many even light weight files, is not a good practice, I know they are light weighted, but this is still too much (even GitHub has trouble displaying them). I don't think it's good idea to merge this into paper in such form. If all 1k files are neccessary, we can keep up on separate branch.
> > 
> > Isn't that the point of DVC to store light index files on version control while data itself is stored somewhere else? and don't we want to have all things relevant to the paper in one place? Generating those images takes long time so it's much better to share them than generate from scratch more than once
> 
> Since these files do not get updated a lot maybe we could zip these files and keep track of one big zip file in dvc. We wouldnt have a mess on dvc then and we would still save all of the data,

Nice idea, why not, works for me

**Comment by Tole-k** [comment]
I packed all data into one zip file

**Review by Dawid64 — APPROVED** [review]
If it's for paper LGTM

**Review by adamtms — APPROVED** [review]
LGTM

**Pull request merged**
